import { useState } from 'react';
import { Bar, BarChart, CartesianGrid, LabelList, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useCalcRun } from '../../shared/calc-run/CalcRunContext';
import { Icon } from '../../shared/ui/Icon';
import { Select } from '../../shared/ui/Select';
import { categories, getDashboardData } from './mockData';

const panel = 'rounded-3xl border border-border bg-surface p-5 sm:p-6';
const tooltipStyle = { background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 16, color: 'var(--text-primary)' };
const axis = { fill: 'var(--text-secondary)', fontSize: 12 };
const number = new Intl.NumberFormat('ru-RU');

export function DashboardPage() {
  const { runs, selectedRunId, isLoading } = useCalcRun();
  const [category, setCategory] = useState('all');
  const [weeks, setWeeks] = useState('8');
  const run = runs.find(item => item.id === selectedRunId);
  if (isLoading || (!selectedRunId && runs.length > 0)) return <div role="status" className="grid gap-4 sm:grid-cols-2"><span className="sr-only">Загрузка аналитики…</span>{[0, 1, 2, 3].map(i => <div key={i} className={`${panel} h-40 animate-pulse`} />)}</div>;
  if (!run) return <div className={panel}><h1 className="text-2xl font-semibold">Дашборд</h1><p className="mt-3 text-text-secondary">Нет доступного расчёта. Выберите расчёт в верхней панели, когда он появится.</p></div>;
  if (run.status !== 'done') return <div role="status" className={panel}><h1 className="text-2xl font-semibold">Аналитика пока недоступна</h1><p className="mt-3 text-text-secondary">{run.status === 'failed' ? 'Выбранный расчёт завершился с ошибкой.' : 'Выбранный расчёт ещё выполняется.'} Выберите готовый расчёт в верхней панели.</p></div>;
  const data = getDashboardData(run.id, run.created_at, category, Number(weeks));
  const date = new Date(run.created_at).toLocaleDateString('ru-RU', { day: '2-digit', month: 'long', timeZone: 'Asia/Almaty' });
  const metrics = [
    { label: 'Позиций к заказу', value: data.orders.length, note: 'SKU в выбранной категории', detail: data.orders.map(p => `${p.sku}: ${number.format(p.quantity)} ${p.unit}`).join(' · ') },
    { label: 'Высокая срочность', value: data.risks.length, note: 'Запас закончится до поставки', detail: 'Текущий остаток / средний дневной спрос меньше срока поставки.' },
    { label: 'Поставщиков', value: data.suppliers.length, note: 'В выбранной категории', detail: data.suppliers.join(' · ') },
    { label: 'Дата расчёта', value: date, note: `Горизонт: ${run.horizon_days} дней`, detail: `Прогон ${run.id}. Показатели на странице — демонстрационные.` },
  ];
  return <div className="space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="mb-3 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-semibold tracking-tight">Дашборд</h1><span className="rounded-full border border-border px-3 py-1 text-xs text-text-secondary">Тестовые данные</span></div><p className="text-sm text-text-secondary">Спрос, закупки и риски дефицита · расчёт от {date}</p></div><Select aria-label="Категория аналитики" options={categories} value={category} onChange={setCategory} /></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((metric, i) => <details key={metric.label} className={panel}><summary className="cursor-pointer list-none rounded-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-focus-ring [&::-webkit-details-marker]:hidden"><div className="flex items-center justify-between gap-2 text-sm text-text-secondary"><span>{metric.label}</span><Icon name={i === 1 || i === 3 ? 'clock' : 'dashboard'} className={i === 1 ? 'text-status-critical' : 'text-text-secondary'} /></div><p className={`my-4 font-semibold tracking-tight ${i === 3 ? 'text-2xl' : 'text-4xl'}`}>{metric.value}</p><p className="text-xs text-text-secondary">{metric.note}</p><span className="mt-3 block text-xs text-accent-text">Показать обоснование ↓</span></summary><p className="mt-4 border-t border-border pt-3 text-sm leading-6 text-text-secondary">{metric.detail}</p></details>)}</div>
    <div className="grid min-w-0 gap-6 xl:grid-cols-2">
      <section className={`${panel} min-w-0`} aria-labelledby="demand-title"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 id="demand-title" className="text-lg font-semibold">Тренд спроса</h2><p className="mt-1 text-xs text-text-secondary">Факт и модельный прогноз · по неделям</p></div><Select aria-label="Период тренда" options={[{ value: '8', label: '8 недель' }, { value: '12', label: '12 недель' }]} value={weeks} onChange={setWeeks} /></div><p className="mt-4 text-xs text-text-secondary">{category === 'all' ? 'Сумма учётных единиц (м и шт.), не денежный объём.' : category === 'cable' ? 'Объём, м' : 'Объём, шт.'}</p>
        <div className="mt-4 h-64 w-full"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.trend} margin={{ top: 12, right: 12, bottom: 8, left: 0 }} accessibilityLayer><CartesianGrid stroke="var(--border)" vertical={false} /><XAxis dataKey="date" tick={axis} tickLine={false} axisLine={false} minTickGap={20} /><YAxis tick={axis} tickLine={false} axisLine={false} width={50} /><Tooltip contentStyle={tooltipStyle} itemStyle={{ color: 'var(--text-primary)' }} cursor={{ stroke: 'var(--border)' }} /><Line name="Факт" type="monotone" dataKey="actual" stroke="var(--chart-series-1)" strokeWidth={3} dot={false} /><Line name="Прогноз" type="monotone" dataKey="forecast" stroke="var(--chart-series-2)" strokeWidth={2} strokeDasharray="6 5" dot={false} /></LineChart></ResponsiveContainer></div>
        <div className="flex justify-center gap-6 text-xs text-text-secondary"><span className="flex items-center gap-2"><span className="w-5 border-t-[3px] border-chart-series-1" />Факт</span><span className="flex items-center gap-2"><span className="w-5 border-t-2 border-dashed border-chart-series-2" />Прогноз</span></div>
        <details className="mt-5 text-sm"><summary className="cursor-pointer rounded focus-visible:ring-2 focus-visible:ring-accent-focus-ring">Данные графика</summary><div className="mt-3 overflow-x-auto"><table className="w-full text-left tabular-nums"><caption className="sr-only">Недельный спрос</caption><thead className="text-text-secondary"><tr><th className="py-2">Неделя</th><th>Факт</th><th>Прогноз</th></tr></thead><tbody>{data.trend.map(p => <tr key={p.date} className="border-t border-border"><td className="py-2">{p.date}</td><td>{number.format(p.actual)}</td><td>{number.format(p.forecast)}</td></tr>)}</tbody></table></div></details>
      </section>
      <section className={`${panel} min-w-0`} aria-labelledby="season-title"><h2 id="season-title" className="text-lg font-semibold">Сезонность</h2><p className="mt-1 text-xs text-text-secondary">Коэффициент спроса по месяцам · 1,0 = базовый уровень</p><div className="mt-8 h-64 w-full"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.seasonality} margin={{ top: 24, right: 4, bottom: 8, left: -20 }} accessibilityLayer><CartesianGrid stroke="var(--border)" vertical={false} /><XAxis dataKey="month" tick={axis} tickLine={false} axisLine={false} interval="preserveStartEnd" /><YAxis tick={axis} domain={[0, 1.6]} tickLine={false} axisLine={false} /><Tooltip contentStyle={tooltipStyle} itemStyle={{ color: 'var(--text-primary)' }} cursor={{ fill: 'var(--page-bg)' }} /><ReferenceLine y={1} stroke="var(--text-secondary)" strokeDasharray="4 4" /><Bar name="Коэффициент" dataKey="coefficient" fill="var(--chart-sequential-500)" radius={[5, 5, 0, 0]}><LabelList dataKey="coefficient" position="top" fill="var(--text-secondary)" fontSize={10} /></Bar></BarChart></ResponsiveContainer></div><p className="mt-4 text-xs leading-5 text-text-secondary">Значение выше 1 означает спрос выше базового. Коэффициенты синтетические, для демонстрации интерфейса.</p></section>
    </div>
    <section className={panel} aria-labelledby="risk-title"><div className="mb-5 flex items-center justify-between gap-4"><div><h2 id="risk-title" className="text-lg font-semibold">Риск дефицита</h2><p className="mt-1 text-sm text-text-secondary">Запас закончится раньше новой поставки · нажмите для обоснования</p></div><span className="rounded-full border border-border px-3 py-1 text-sm tabular-nums">{data.risks.length} SKU</span></div>
      {data.risks.length === 0 ? <p className="py-6 text-text-secondary">Нет позиций с высоким риском дефицита.</p> : <div className="divide-y divide-border">{data.risks.map(p => <details key={`${run.id}-${p.sku}`} className="group py-4"><summary className="flex cursor-pointer list-none flex-wrap items-center justify-between gap-4 rounded-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-focus-ring [&::-webkit-details-marker]:hidden"><div><p className="text-sm font-semibold">{p.name}</p><p className="mt-1 text-xs text-text-secondary">{p.sku} · {p.supplier}</p></div><div className="flex flex-wrap items-center gap-4 text-sm"><span className="tabular-nums">Запас на {p.daysLeft.toLocaleString('ru-RU')} дн.</span><span className="flex items-center gap-2 rounded-full border border-border px-3 py-1 text-xs text-text-secondary"><Icon name="clock" className="text-status-critical" width={16} height={16} />Высокая срочность</span><Icon name="arrow" className="text-text-secondary group-open:rotate-90" /></div></summary><div className="mt-4 rounded-2xl bg-page-bg p-4 text-sm leading-6 text-text-secondary"><p>Остаток: {p.stock} {p.unit} ÷ спрос: {p.daily} {p.unit}/день = запас на {p.daysLeft.toLocaleString('ru-RU')} дн. Срок поставки: {p.lead} дн.</p><p>К заказу: <strong className="text-text-primary">{number.format(p.quantity)} {p.unit}</strong> — спрос на срок поставки и 7 дней буфера за вычетом остатка.</p></div></details>)}</div>}
      <p className="mt-4 border-t border-border pt-4 text-xs text-text-secondary">Демонстрационный сценарий. Данные не отражают реальные остатки.</p>
    </section>
  </div>;
}
